### ISSUE TITLE
some characters need to be escaped (i.e. \)

### ISSUE THREAD

**Issue by emmapeel2** [numericube/lektor-i18n-plugin#16]
When generating the contents.pot file, the characters like \ and others are not escaped, so the translation apps fail and the translation breaks, or some characters dissapear.

When generating the translation strings, those characters should follow the specifications for .po files.

**Comment by odeckmyn** [comment]
Would you provide a fix for this one ? We would be happy to merge  !

**Comment by emmapeel2** [comment]
ok, here a patch with the help of https://github.com/boklm . thanks boklm!

**Comment by gusgustavo** [comment]
Hi @odeckmyn, could you merge emmapeel's pull request?

https://github.com/numericube/lektor-i18n-plugin/pull/17
